steps:
  - name: Setup Slate docs.
    plugin: Script
    script: |
      ln -s $SRC_DIR /var/www/html
      chown www-data:www-data $SRC_DIR
      cd $SRC_DIR
      gem update --system
      gem install bundler
      bundle install
      bundle exec middleman build --clean
